// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMd0sNj289rlNfWVX0m-h17uyjw4bVsw',
    appId: '1:867788434091:web:950d047e5a6f238966e5ee',
    messagingSenderId: '867788434091',
    projectId: 'the-dining-atlas',
    authDomain: 'the-dining-atlas.firebaseapp.com',
    storageBucket: 'the-dining-atlas.firebasestorage.app',
    measurementId: 'G-WJYZMXHJSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABo27TYASCMYWsA-cCmYEVjXCpC0rFo9s',
    appId: '1:867788434091:android:b3dde503cf316f1966e5ee',
    messagingSenderId: '867788434091',
    projectId: 'the-dining-atlas',
    storageBucket: 'the-dining-atlas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjf5H4qFiJOCWGbA8OFXShrz69GVOn6Sc',
    appId: '1:867788434091:ios:af21fd4b3229d4af66e5ee',
    messagingSenderId: '867788434091',
    projectId: 'the-dining-atlas',
    storageBucket: 'the-dining-atlas.firebasestorage.app',
    iosBundleId: 'com.example.diningAtlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjf5H4qFiJOCWGbA8OFXShrz69GVOn6Sc',
    appId: '1:867788434091:ios:af21fd4b3229d4af66e5ee',
    messagingSenderId: '867788434091',
    projectId: 'the-dining-atlas',
    storageBucket: 'the-dining-atlas.firebasestorage.app',
    iosBundleId: 'com.example.diningAtlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoMd0sNj289rlNfWVX0m-h17uyjw4bVsw',
    appId: '1:867788434091:web:460aeee2f93180df66e5ee',
    messagingSenderId: '867788434091',
    projectId: 'the-dining-atlas',
    authDomain: 'the-dining-atlas.firebaseapp.com',
    storageBucket: 'the-dining-atlas.firebasestorage.app',
    measurementId: 'G-1747Z6S8Q3',
  );
}
